OPENCV_LIBS = -lopencv_imgcodecs -lopencv_imgproc -lopencv_core -lopencv_highgui -lopencv_videoio -lopencv_calib3d -lopencv_features2d
 
FILES = test.cpp

all:
	$(CXX) $(FILES) -o test $(OPENCV_LIBS)

clean :
	rm test
